spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092, localhost:9094, localhost:9096}

app:
  kafka:
    topics:
      bank-account-opened:
        topic-name: ${KAFKA_BANK_ACCOUNT_OPENED_TOPIC_NAME:bank-account-opened}
      bank-account-activated:
        topic-name: ${KAFKA_BANK_ACCOUNT_ACTIVATED_TOPIC_NAME:bank-account-activated}
      bank-account-blocked:
        topic-name: ${KAFKA_BANK_ACCOUNT_BLOCKED_TOPIC_NAME:bank-account-blocked}
      joint-account-holder-added:
        topic-name: ${KAFKA_JOINT_ACCOUNT_HOLDER_ADDED_TOPIC_NAME:joint-account-holder-added}

cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION:us-east-1}
    credentials:
      access-key-id: ${AWS_ACCESS_KEY_ID:test}
      secret-key: ${AWS_SECRET_ACCESS_KEY:test}
    dynamodb:
      endpoint: ${AWS_DYNAMODB_ENDPOINT:http://127.0.0.1:4567}
      tables:
        banking-entities:
          table-name: ${AWS_DYNAMODB_BANKING_ENTITIES_TABLE_NAME:banking-entities}
