services:

  localstack:
    container_name: "bank-accounts-localstack-4.6.0"
    image: localstack/localstack:4.6.0
    ports:
      - '127.0.0.1:4566:4566'
    environment:
      SERVICES: dynamodb
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      LS_LOG: ${LS_LOG:-debug}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bank_accounts_network
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./localstack:/etc/localstack/init/ready.d
      - bank_accounts_localstack-volume:/var/lib/localstack

  kafka-1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: bank-accounts-kafka-1
    hostname: kafka-1
    networks:
      - bank_accounts_network
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: >
        1@kafka-1:9093

      KAFKA_LISTENERS: >
        PLAINTEXT://kafka-1:29092,
        PLAINTEXT_HOST://0.0.0.0:9092,
        CONTROLLER://kafka-1:9093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka-1:29092,
        PLAINTEXT_HOST://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - bank_accounts_kafka_1_volume:/var/lib/kafka/data

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    container_name: bank-accounts-kafka-init
    restart: no
    depends_on:
      - kafka-1
    networks:
      - bank_accounts_network
    volumes:
      - ./kafka/01-create-topics.sh:/usr/local/bin/01-create-topics.sh
    entrypoint: [ "/bin/bash", "/usr/local/bin/01-create-topics.sh" ]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: bank-accounts-kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: >
        kafka-1:29092
    networks:
      - bank_accounts_network

volumes:
  bank_accounts_localstack-volume:
    name: bank-accounts-localstack-data
  bank_accounts_kafka_1_volume:
    name: bank-accounts-kafka-1-data

networks:
  bank_accounts_network:
    name: bank-accounts-network